import React from "react"

type Style = {
    height?: string
    width?: string
    marginTop?: string
    marginRight?: string
    marginLeft?: string
    marginInline?: string
    scale?: number
}

type TechType =
    | "library"
    | "framework"
    | "language"
    | "api"
    | "database"
    | "css"
    | "other"

type platformType = "web" | "mobile" | "desktop" | "email" | "other"

type Tech = {
    name: string
    webLink: string
    imgSrc: string
    tooltipRef: string
    projectFilter: boolean
    currentStack: boolean
    platformType: platformType[]
    type: TechType
    hide?: boolean
    invert?: boolean
    style?: Style | string
    className?: string
    imageStyle?: Style | string
    imageClassName?: string
}

export const techList: Tech[] = [
    {
        name: "Figma",
        webLink: "https://www.figma.com/?fuid=",
        imgSrc: "https://i.ibb.co/0FJ39J4/png-transparent-figma-app-logo-tech-companies-thumbnail.png",
        tooltipRef: "figma",
        currentStack: true,
        platformType: ["web", "mobile", "desktop"],
        projectFilter: false,
        type: "other",
        style: {
            height: "48px",
            marginTop: "0px",
            width: "52px",
        },
        className: "",
        imageClassName: "",
    },
    {
        name: "HTML",
        imgSrc: "https://img.icons8.com/color/48/000000/html-5.png",
        tooltipRef: "html",
        projectFilter: false,
        platformType: ["web"],
        type: "other",
        webLink:
            "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
        currentStack: false,
        style: "fab fa-html5",
        className: "",
        imageClassName: "",
    },
    {
        name: "CSS",
        webLink: "https://www.w3schools.com/css/",
        imgSrc: "https://img.icons8.com/color/48/000000/css3.png",
        type: "css",
        platformType: ["web"],
        projectFilter: false,
        tooltipRef: "css",
        currentStack: false,
        imageClassName: "",
    },
    {
        name: "Bootstrap",
        webLink: "https://getbootstrap.com",
        imgSrc: "https://img.icons8.com/color/48/000000/bootstrap.png",
        projectFilter: false,
        platformType: ["web"],
        tooltipRef: "bootstrap",
        type: "library",
        currentStack: false,
        style: {
            height: "48px",
            marginTop: "0px",
            width: "52px",
        },
        imageClassName: "",
    },
    {
        name: "Gulp",
        webLink: "https://gulpjs.com/",
        imgSrc: "https://i.ibb.co/n6N253V/gulp-copy.png",
        tooltipRef: "gulp",
        platformType: ["web"],
        projectFilter: false,
        type: "other",
        currentStack: false,
        className: "",
        imageStyle: {
            height: "40px",
            marginTop: "3px",
            width: "42px",
        },
        imageClassName: "",
    },
    {
        name: "Sass",
        webLink: "https://sass-lang.com/",
        imgSrc: "https://img.icons8.com/color/48/000000/sass.png",
        tooltipRef: "sass",
        platformType: ["web"],
        projectFilter: true,
        type: "css",
        currentStack: false,
        style: {
            height: "48px",
            marginTop: "0px",
            width: "52px",
        },
        imageClassName: "h-30 ",
    },
    {
        name: "Javascript",
        webLink: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        imgSrc: "https://img.icons8.com/color/48/000000/javascript.png",
        tooltipRef: "javascript",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: true,
        type: "language",
        currentStack: false,
        className: "",
        imageClassName: "",
    },
    {
        name: "Git",
        webLink: "https://git-scm.com/",
        imgSrc: "https://img.icons8.com/color/48/000000/git.png",
        tooltipRef: "git",
        platformType: ["web", "mobile", "desktop", "email"],
        projectFilter: false,
        type: "other",
        currentStack: false,
        className: "",
        imageClassName: "",
    },
    {
        name: "Webpack",
        webLink: "https://webpack.js.org/",
        imgSrc: "https://i.ibb.co/h7R2dLL/webpack.png",
        tooltipRef: "webpack",
        platformType: ["web"],
        projectFilter: false,
        type: "other",
        currentStack: false,
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
    },
    {
        name: "D3.js",
        webLink: "https://d3js.org/",
        imgSrc: "https://i.ibb.co/MCHcY6D/d3.png",
        tooltipRef: "D3.js",
        platformType: ["web"],
        projectFilter: false,
        type: "library",
        currentStack: false,
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
    },
    {
        name: "Typescript",
        webLink: "https://www.typescriptlang.org/",
        imgSrc: "https://i.ibb.co/hyG9DhN/typescript.png",
        tooltipRef: "typescript",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: true,
        type: "language",
        currentStack: true,
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
    },
    {
        name: "React",
        webLink: "https://reactjs.org/",
        type: "framework",
        projectFilter: true,
        imgSrc: "https://img.icons8.com/color/48/000000/react-native.png",
        tooltipRef: "react",
        platformType: ["web", "mobile", "desktop", "email"],
        currentStack: false,
    },
    {
        name: "Next.js",
        webLink: "https://nextjs.org/",
        imgSrc: "https://img.icons8.com/color/48/000000/nextjs.png",
        tooltipRef: "next",
        invert: true,
        platformType: ["web"],
        projectFilter: true,
        currentStack: true,
        type: "framework",
        imageClassName: "dark:grayscale dark:invert",
    },
    {
        name: "Redux",
        webLink: "https://redux.js.org",
        imgSrc: "https://img.icons8.com/color/48/000000/redux.png",
        tooltipRef: "redux",
        platformType: ["web"],
        projectFilter: false,
        currentStack: false,
        type: "other",
    },
    {
        name: "Tailwind",
        webLink: "https://tailwindcss.com/",
        imgSrc: "https://img.icons8.com/color/48/000000/tailwindcss.png",
        tooltipRef: "tailwind",
        projectFilter: true,
        platformType: ["web", "mobile"],
        currentStack: false,
        type: "css",
    },
    {
        name: "Tailwind UI",
        webLink: "https://tailwindui.com/",
        imgSrc: "https://i.ibb.co/stC8B8h/tailwind-u-I.png",
        tooltipRef: "tailwindui",
        platformType: ["web"],
        projectFilter: false,
        hide: true,
        currentStack: false,
        type: "library",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
    },
    {
        name: "Node.js",
        webLink: "https://nodejs.org",
        imgSrc: "https://img.icons8.com/color/48/000000/nodejs.png",
        tooltipRef: "node",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: false,
        hide: true,
        currentStack: false,
        type: "framework",
        className: "ml-2 mt-1 px-1 pb-[-4px] pt-[1px] dark:bg-white",
    },
    {
        name: "Firebase",
        webLink: "https://firebase.google.com/",
        imgSrc: "https://img.icons8.com/color/48/000000/firebase.png",
        tooltipRef: "firebase",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: true,
        currentStack: true,
        type: "database",
        imageClassName: "scale-90 mt-1",
    },
    {
        name: "Supabase",
        webLink: "https://supabase.com/",
        imgSrc: "https://i.ibb.co/Yjn0Nbx/supabase.png",
        tooltipRef: "supabase",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: true,
        currentStack: true,
        type: "database",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
        imageClassName: "mr-2",
    },
    {
        name: "Postman",
        webLink: "https://postman.com",
        imgSrc: "https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg",
        tooltipRef: "postman",
        platformType: ["other"],
        projectFilter: false,
        currentStack: false,
        type: "other",
        imageStyle: "mt-2 mr-2 h-[45px] w-[45px]",
    },
    {
        name: "Vercel",
        webLink: "https://vercel.com",
        imgSrc: "https://i.ibb.co/4jSbQ3t/vercel.png",
        tooltipRef: "vercel",
        platformType: ["other"],
        projectFilter: false,
        currentStack: true,
        type: "other",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
        imageClassName: "mr-2",
    },
    {
        name: "T3 App",
        webLink: "https://create.t3.gg/",
        imgSrc: "https://i.ibb.co/CPTK4xm/t3.png",
        tooltipRef: "t3",
        platformType: ["web"],
        projectFilter: false,
        currentStack: false,
        type: "framework",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
        imageClassName: "mr-2",
    },
    {
        name: "Prisma",
        webLink: "https://www.prisma.io/",
        imgSrc: "https://i.ibb.co/xj61MMr/prisma-logo-3805665-B69-seeklogo-com-2.png",
        tooltipRef: "prisma",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: false,
        currentStack: false,
        type: "other",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
        imageClassName: "mr-2 dark:invert scale-75",
    },
    {
        name: "PlanetScale",
        webLink: "https://planetscale.com",
        imgSrc: "https://i.ibb.co/X3Xjk9w/planetscale-logo-0-EEA8-CAEB4-seeklogo-com.png",
        tooltipRef: "planetscale",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: true,
        invert: true,
        currentStack: false,
        type: "database",
        imageStyle: {
            height: "40px",
            marginTop: "7px",
        },
        imageClassName: "mr-2 dark:invert",
    },
    {
        name: "Upstash",
        webLink: "https://Upstash.com",
        imgSrc: "https://i.ibb.co/PFcgZPb/upstash-icon-logo-6-EB6-AA96-EE-seeklogo-com.png",
        tooltipRef: "upstash",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: false,
        currentStack: false,
        type: "database",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
        imageClassName: "mr-2 scale-75 mt-2",
    },
    {
        name: "SendGrid",
        webLink: "https://sendgrid.com/",
        imgSrc: "https://i.ibb.co/y4ZP2qG/sendgrid.png",
        tooltipRef: "sendgrid",
        platformType: ["email"],
        projectFilter: false,
        currentStack: false,
        type: "api",
        className: "",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
        imageClassName: "mr-2 mt-2",
    },
    {
        name: "Resend (Email API)",
        webLink: "https://resend.com",
        imgSrc: "https://i.ibb.co/D4vWKKH/rmsjyqmeisecrvzmnpik.webp",
        tooltipRef: "resend",
        platformType: ["email"],
        projectFilter: false,
        currentStack: true,
        type: "api",
        imageClassName: "scale-80 mt-2 mr-1.5 h-10",
    },
    {
        name: "React Email",
        webLink: "https://react.email/",
        imgSrc: "https://i.ibb.co/qMSFHVM/reactemail.png",
        tooltipRef: "reactemail",
        platformType: ["email"],
        projectFilter: false,
        currentStack: false,
        type: "other",
        imageStyle: {
            height: "50px",
            marginTop: "3px",
        },
        imageClassName: "mt-2.5",
    },
    {
        name: "AWS Amplify",
        webLink: "https://aws.amazon.com/amplify/",
        imgSrc: "https://i.ibb.co/WycSHZ9/aws-amplify-logo-D68-DDB5-AB1-seeklogo-com.png",
        tooltipRef: "aws",
        platformType: ["web", "mobile", "desktop"],
        projectFilter: true,
        currentStack: false,
        type: "database",
        imageStyle: {
            height: "35px",
            marginTop: "16px",
            marginRight: "6px",
        },
        imageClassName: "mt-2",
    },
    {
        name: "React Native",
        webLink: "https://reactnative.dev",
        imgSrc: "https://i.ibb.co/YdCjKL5/react-native-dark-poster-with-blue-icon-on-black-vector-36271615.jpg",
        tooltipRef: "reactnative",
        platformType: ["mobile"],
        projectFilter: true,
        currentStack: true,
        type: "framework",
        style: {
            height: "35px",
            marginTop: "3px",
            width: "45px",
            marginInline: "5px 7px",
        },
        imageClassName: " mt-2 rounded-md",
    },
    {
        name: "Expo",
        webLink: "https://expo.dev",
        imgSrc: "https://i.ibb.co/4MkCpYb/expo.png",
        tooltipRef: "expo",
        invert: true,
        platformType: ["mobile"],
        projectFilter: false,
        currentStack: true,
        type: "other",
        style: {
            height: "35px",
            marginTop: "3px",
            width: "45px",
            marginInline: "5px 7px",
        },
        imageClassName: "mt-2 dark:opacity-70 dark:invert",
    },
    {
        name: "Swift",
        webLink: "https://www.swift.org",
        imgSrc: "https://i.ibb.co/47kFpFW/swift-logo.png",
        tooltipRef: "swift",
        platformType: ["mobile", "desktop", "other"],
        projectFilter: true,
        currentStack: true,
        type: "language",
        imageClassName: "mt-2 h-[45px] w-[45px]",
    },
    {
        name: "Swift UI",
        webLink: "https://www.swift.org",
        imgSrc: "https://i.ibb.co/dczJQSP/swiftui-og.png",
        tooltipRef: "swiftui",
        platformType: ["mobile", "desktop", "other"],
        projectFilter: false,
        hide: true,
        currentStack: false,
        type: "other",
        className: "ml-2 mt-1 px-1 pb-[-4px]",
        imageClassName: "mt-1.5 mr-2 h-[45px] w-[45px]",
    },
    {
        name: "Three.js",
        webLink: "https://threejs.org",
        imgSrc: "https://i.ibb.co/vHhzghj/threeJS.png",
        tooltipRef: "threejs",
        projectFilter: false,
        platformType: ["web", "mobile"],
        currentStack: false,
        // style: {
        //     height: "48px",
        //     marginTop: "0px",
        //     width: "52px",
        // },
        type: "library",
        className: "",
        imageStyle: "",
        imageClassName: "scale-75 mt-2",
    },
    {
        name: "React-Three-Fiber",
        webLink:
            "https://docs.pmnd.rs/react-three-fiber/getting-started/introduction",
        imgSrc: "https://i.ibb.co/0XBqzYg/react-three-fiber.png",
        tooltipRef: "threeFiber",
        projectFilter: false,
        platformType: ["web", "mobile"],
        currentStack: false,
        // style: {
        //     height: "48px",
        //     marginTop: "0px",
        //     width: "52px",
        // },
        type: "library",
        className: "",
        imageStyle: "",
        imageClassName: "mt-2",
    },
    {
        name: "ThreeDrei",
        webLink:
            "https://drei.pmnd.rs/?path=/docs/staging-accumulativeshadows--docs",
        imgSrc: "https://i.ibb.co/v18T12f/react-drei.png",
        tooltipRef: "threeDrei",
        projectFilter: false,
        platformType: ["web"],
        currentStack: false,
        // style: {
        //     height: "48px",
        //     marginTop: "0px",
        //     width: "52px",
        // },
        type: "library",
        className: "",
        imageStyle: "",
        imageClassName: "mt-2",
    },
]

const copy = [
    {
        name: "",
        webLink: "",
        imgSrc: "",
        tooltipRef: "",
        projectFilter: false,
        currentStack: false,
        platformType: ["web", "mobile", "desktop", "email", "other"],
        type: [
            "library",
            "framework",
            "language",
            "api",
            "database",
            "css",
            "other",
        ],
        style: {
            height: "48px",
            marginTop: "0px",
            width: "52px",
        },
        className: "",
        imageStyle: "",
        imageClassName: "",
    },
]
